//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone_Application_Draft2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Months_Until
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Months_Until()
        {
            this.Userinfoes = new HashSet<Userinfo>();
            this.Stuff_To_Do = new HashSet<Stuff_To_Do>();
        }
    
        public int Months_Until_ID { get; set; }
        public string Months { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Userinfo> Userinfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stuff_To_Do> Stuff_To_Do { get; set; }
    }
}
